vim.o.signcolumn = "no"
vim.o.incsearch = true
vim.o.number = true
vim.o.relativenumber = true
vim.o.wrap = false
vim.o.swapfile = false
vim.o.backup = false
vim.o.undodir = os.getenv("HOME") .. "/.vim/undodir"
vim.o.autochdir = true
-- vim.o.undofile = true
-- vim.o.tabstop = 2
-- vim.o.shiftwidth = 2
-- vim.o.expandtab = true
